### ISSUE TITLE
QNAP-T310G1T not recognized in esxi 6.7

### ISSUE THREAD

**Issue by dblosvn** [Aquantia/AQtion-esxi#10]
The driver module is loaded but I do not see the device in the network adapter list

Driver shown is motherboard device:
[root@fcy-mac01:~] localcli network nic list
Name    PCI Device    Driver  Admin Status  Link Status  Speed  Duplex  MAC Address        MTU   Description
------------------------------------------------------------------------------------------------------------
vmnic0  0000:04:00.0  tg3     Up            Up            1000  Full    80:4a:14:63:b0:73  1500  Broadcom Corporation NetXtreme BCM57766 Gigabit Ethernet

driver module shows loaded:

[root@fcy-mac01:~] esxcli software vib list | grep -i aqua
net-atlantic                   v2.2.3.0-esxi1.6                      Aquantia  CommunitySupported  2019-09-10

Am I missing something super simple here?

**Comment by cail** [comment]
AFAIK ESXi on macos has some issues with thunderbolt stack.
Do you see AQ device being listed with `lspci`? If no - thats a thunderbolt stack issues

**Comment by dblosvn** [comment]
I do not see it in the list for lspci



Bryan Bond


________________________________

**Comment by cail** [comment]
and this means you have to contact vmware to find out how to make TB device to be recognized by esxi.
