### ISSUE TITLE
Can't Add to 6.7 Update Manager

### ISSUE THREAD

**Issue by frozenak** [Aquantia/AQtion-esxi#11]
The vendor-index.xml look like they need to be updated to add the offline bundle in to vCenter Update Manager.
net670-atlantic-v2.2.3.0-esxi1.6.x86_x64-offline-bundle.zip\vendor-index.xml
net670-atlantic-v2.2.3.0-esxi1.6.x86_x64-offline-bundle\metadata.zip\vendor-index.xml

They show only 5.*
    <version>5.*</version>

net-atlantic.xml has the same thing.
net670-atlantic-v2.2.3.0-esxi1.6.x86_x64-offline-bundle.zip\metadata.zip\bulletins\net-atlantic.xml
version="5.*" 

I manually updated those to 6.* and then I was able to import the offline bundle in to vCenter 6.7 Update Manager.

**Comment by phil-bypip-ltd** [comment]
Hi, ive tried this too, but when I try to upload I get an error saying "Cannot upload file, as it is an invalid package". Can you share your updated zip file please? Thank you

**Comment by frozenak** [comment]
> Hi, ive tried this too, but when I try to upload I get an error saying "Cannot upload file, as it is an invalid package". Can you share your updated zip file please? Thank you

I can get it this weekend. Had a power outage the other day and haven't booted the lab back up.
If I remember correctly, I got that error message when even one of the files only had version 5 in it.
Once all 3 were modified I was able to upload without issue.

**Comment by dimbez** [comment]
Hello, please download native driver from https://www.vmware.com/resources/compatibility/search.php?deviceCategory=io&details=1&releases=369&VID=1d6a&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc
