### ISSUE TITLE
Troubles with management network on VLAN

### ISSUE THREAD

**Issue by quacktacular** [Aquantia/AQtion-esxi#12]
Trying to run the 1.6 release on a 2018 10gbe Mac mini runninig ESXi 6.7u3. My management network is on a tagged VLAN. This seems to work alright, but after a restart the network becomes unreachable until I change the IP of the host. Can't ping outbound or inbound.

No other devices (Supermicros also running 6.7u3) connected to my ten gigabit switch (Turboiron) have issues. 

Edit: toggling DHCP on and back to manual seems to work sometimes as well. Restarting the network doesn't seem to help. Any ideas?

**Comment by dimbez** [comment]
Hello @quacktacular, sorry for delayed response. To resolve your problem please try to update driver to native, you can find it at the following [link](https://www.vmware.com/resources/compatibility/search.php?deviceCategory=io&details=1&VID=1d6a&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc)
