### ISSUE TITLE
Maintenance after Marvell takeover

### ISSUE THREAD

**Issue by jdrozdnovak** [Aquantia/AQtion-esxi#15]
Hello,
Do you know if there will be some development after we changed the name to Marvell? :)

**Comment by dimbez** [comment]
@blackcult, yes. If you need native driver, please find it at the following [link](https://www.vmware.com/resources/compatibility/search.php?deviceCategory=io&details=1&VID=1d6a&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc)
