### ISSUE TITLE
ESXi 7.0 Support

### ISSUE THREAD

**Issue by jmgilman** [Aquantia/AQtion-esxi#16]
Any plans to add support for ESXi 7?

**Comment by jdrozdnovak** [comment]
esxi7 no longer support vmklinux drivers.
However there is a certification in progress for native drivers for aquantia chips.
However no idea when that will be.

**Comment by dimbez** [comment]
Hello @jmgilman , please find native 7.0 driver at the following [link](https://www.vmware.com/resources/compatibility/search.php?deviceCategory=io&details=1&VID=1d6a&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc)
