### ISSUE TITLE
Installed but not working

### ISSUE THREAD

**Issue by Astral1020** [Aquantia/AQtion-esxi#17]
ESXi 6.7 U3

`lspci -v`

> 0000:04:00.0 Network controller Ethernet controller: Aquantia Corp. AQC108 NBase-T/IEEE 802.3bz Ethernet Controller [AQtion] [vmnic1]
	 Class 0200: 1d6a:d108

after install the vib file from https://github.com/Aquantia/AQtion-esxi/releases/download/v2.2.3.0-esxi1.6/net670-atlantic-v2.2.3.0-esxi1.6.x86_x64.vib

`esxcli software vib list`

> Name                           Version                               Vendor    Acceptance Level    Install Date
-----------------------------  ------------------------------------  --------  ------------------  ------------AquantiaAQN107                 2.0.22.017                            Aquantia  CommunitySupported  2020-04-11

`esxcfg-nics -l`
Still not don't have AQC108

what should I do to add it to ESXi?

**Comment by dimbez** [comment]
Hello, @Astral1020, please find native driver at the following [link](https://www.vmware.com/resources/compatibility/search.php?deviceCategory=io&details=1&VID=1d6a&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc). You need to remove current driver, install new, reboot PC and then NIC devices will be shown.
