### ISSUE TITLE
Issues with MTU sizes greater than 1500 bytes

### ISSUE THREAD

**Issue by kurthv** [Aquantia/AQtion-esxi#19]
I am using the VMware ESXi 6.7 atlantic 1.0.2.0 Driver for AQtion Ethernet Controllers (https://bit.ly/3cKY7SL) in combination with a Sonnet Solo 10G network adapter.

Everthing is working as supposed as long as I don't change the MTU to a value greater than 1500bytes. If I do so, I have TCP connectivity issues and massive performance degradation.

A packet capture shows a lot of duplicate ACK packets and retransmission.
Please have a look at the attached packet dumps.

[packet-dump.zip](https://github.com/Aquantia/AQtion-esxi/files/5300116/packet-dump.zip)

**Comment by dimbez** [comment]
Hi @kurthv,
Please describe how do you change MTU ?

**Comment by kurthv** [comment]
I changed the MTU on the vCenter Distributed Switch.

**Comment by dimbez** [comment]
Hi @kurthv, where is traffic terminated? If it vmk interface please change MTU at vmk interface as well. If it's VM - please change MTU at VM  interface.

**Comment by kurthv** [comment]
Hi @dimbez , I did try all conceivable combinations -> nothing really worked well :(
With other NICs (e.g. the internal 1Gbit Intel NIC), I don't have these issues.

**Comment by dimbez** [comment]
Hi, @kurthv, prease write me directly to email - dbezrukov@marvell.com. Will discuss next steps
