### ISSUE TITLE
Cannot install the driver on ESXi 7.0

### ISSUE THREAD

**Issue by ldes89150** [Aquantia/AQtion-esxi#20]
I got the following error while trying to install the driver on ESXi 7.0

Could you please let me know how to resolve this issue? Thanks!
```
[root@localhost:/vmfs/volumes/5fa46b65-a0dc35e4-7431-a8a15942a245] esxcli software vib install -d /vmfs/volumes/datastore1/net670-atlantic-v2.2.3.0-esxi1.6.x86_x64-offline-bundle.zip 
 [DependencyError]
 VIB Aquantia_bootbank_net-atlantic_v2.2.3.0-esxi1.6 requires vmkapi_2_3_0_0, but the requirement cannot be satisfied within the ImageProfile.
 Please refer to the log file for more details.
```

**Comment by ldes89150** [comment]
I found this on vmware's website.
https://www.vmware.com/resources/compatibility/detail.php?deviceCategory=io&productid=50142&releaseid=508&deviceCategory=io&details=1&VID=1d6a&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc

However, the download link is not working.

**Comment by lamw** [comment]
You should be installing the official ESXi Native Driver from Marvell - https://my.vmware.com/en/web/vmware/details?downloadGroup=DT-ESXI67-MARVELL-ATLANTIC-1020&productId=742 (although it says 6.7, it should work for 7.0)

**Comment by 0dragosh** [comment]
@lamw Link seems dead
<img width="1504" alt="Screenshot 2020-11-15 at 00 12 19" src="https://user-images.githubusercontent.com/39906742/99158053-4b6a1680-26d7-11eb-94b1-1943a91d875c.png">

**Comment by redreinard** [comment]
> @lamw Link seems dead
> <img alt="Screenshot 2020-11-15 at 00 12 19" width="1504" src="https://user-images.githubusercontent.com/39906742/99158053-4b6a1680-26d7-11eb-94b1-1943a91d875c.png">

Log into vmware with your active account first, then visit the link. Confirmed working then.

**Comment by dimbez** [comment]
Hi @ldes89150, driver from repository is linux based. Starting from 7.0 linux based driver is no longer supported. Please download driver which supports native API from site: [download](https://www.vmware.com/resources/compatibility/search.php?deviceCategory=io&details=1&VID=1d6a&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc)

@0dragosh, @redreinard Please follow to the same.
