### ISSUE TITLE
Fail to install driver on ESXI 8.0 Update 2

### ISSUE THREAD

**Issue by galvesribeiro** [Aquantia/AQtion-esxi#24]
Hello!

I'm trying to install this driver so I can get my motherboard 10G NIC to work on ESXI 8. The motherboard is an ASUS ProArt X670E-CREATOR WIFI which has a "**Marvell® AQtion 10Gb Ethernet**".

I've download the latest release on GitHub `net670-atlantic-v2.2.3.0-esxi1.6.x86_x64.vib` but when I try to install it I get this:

```
[root@GUTO-ESX-01:/vmfs/volumes/65d24748-e2d54ccc-b4a8-e89c25277298] esxcli software vib install -f -v ${PWD}/net670-atlantic-v2.2.3.0-esxi1.6.x86_x64.vib
 [ProfileValidationError]
 In ImageProfile (Updated) ESXi-8.0U2-22380479-standard, the payload(s) in VIB Aquantia_bootbank_net-atlantic_v2.2.3.0-esxi1.6 does not have sha-256 gunzip checksum. This will prevent VIB security verification and secure boot from functioning properly. Please remove this VIB or please check with your vendor for a replacement of this VIB
 Please refer to the log file for more details.
```

I've already set the acceptance level to `CommunitySupported`. Do I need anything else?

Thank you!

**Comment by dimbez** [comment]
Hi, @galvesribeiro 
ESXi8 should have support of Marvell AQtion devices based on AQC107 chips. You dont need to install this driver. This driver uses legacy mode of linux like drivers support. It's not supported by modern ESXi kernels anymore (was introduced somewhere starting 6+ kernel)

**Comment by galvesribeiro** [comment]
Hi @dimbez. 

That is good. However, that motherboard has two NICs, one Intel 2.5G and that AQtion 10Gb. The Intel works just fine, but the AQtion is never detected :(

**Comment by dimbez** [comment]
@galvesribeiro it might be AQC113 based device. Please share PCIe device ID of your AQtion device.

**Comment by galvesribeiro** [comment]
Just booted a live linux ISO and lspci tells me it is a"AQC113CS NBase-T/IEEE 802.3bz Ethernet Controller [AQtion]" with device id 94C0.

**Comment by dimbez** [comment]
Unfortunately aqc113 based devices are not supported.

**Comment by galvesribeiro** [comment]
Ok :( Thank you!

**Comment by GoodGas** [comment]
> Hello!
> 
> I'm trying to install this driver so I can get my motherboard 10G NIC to work on ESXI 8. The motherboard is an ASUS ProArt X670E-CREATOR WIFI which has a "**Marvell® AQtion 10Gb Ethernet**".
> 
> I've download the latest release on GitHub `net670-atlantic-v2.2.3.0-esxi1.6.x86_x64.vib` but when I try to install it I get this:
> 
> ```
> [root@GUTO-ESX-01:/vmfs/volumes/65d24748-e2d54ccc-b4a8-e89c25277298] esxcli software vib install -f -v ${PWD}/net670-atlantic-v2.2.3.0-esxi1.6.x86_x64.vib
>  [ProfileValidationError]
>  In ImageProfile (Updated) ESXi-8.0U2-22380479-standard, the payload(s) in VIB Aquantia_bootbank_net-atlantic_v2.2.3.0-esxi1.6 does not have sha-256 gunzip checksum. This will prevent VIB security verification and secure boot from functioning properly. Please remove this VIB or please check with your vendor for a replacement of this VIB
>  Please refer to the log file for more details.
> ```
> 
> I've already set the acceptance level to `CommunitySupported`. Do I need anything else?
> 
> Thank you!

Hello, friend, have you found the ESXi image supported by the asus proart x670e wifi yet?

**Comment by galvesribeiro** [comment]
Nop. It is not supported as mentioned. I gave up.

**Comment by GoodGas** [comment]
> Nop. It is not supported as mentioned. I gave up.

I am trying. If I can find it, I will share it with you, friend.
