### ISSUE TITLE
Lots of errors on the wire

### ISSUE THREAD

**Issue by maskato** [Aquantia/AQtion-esxi#3]
Wireshark pcap attached. Embedded Host Client won't even log in. SSH works okay. Please let me know if I can do anything to help isolate the problem. When I passthrough the adapter to a Linux VM, it works fine. ESXi 6.7.0 Update 2 (Build 13006603).
[aqn-107.zip](https://github.com/Aquantia/AQtion-esxi/files/3099265/aqn-107.zip)

**Comment by maskato** [comment]
Changed MTU back to 1500, same issues. SSH seems to work ok, but there are errors on the wire as well.
[aqn-107-1500.zip](https://github.com/Aquantia/AQtion-esxi/files/3099384/aqn-107-1500.zip)

**Comment by dimbez** [comment]
Hi, @maskato.
Which is device as link partner for AQN NIC?
On which side the first dump was collected?
What is the session in the first dump? Was AQN used as a management device at this case?

**Comment by maskato** [comment]
Hi @dbezrukovaquantia,

The partner is a Sonnet Solo 10G (also AQN-based). Both are connected to an
HPE 1850 10G switch.

All dumps were taken on the Sonnet-side.

The first session was trying to connect to the management GUI via HTTPS.

Before I installed the ESXi driver, I passed the NIC thru to a Linux VM and
it worked fine.

**Comment by dimbez** [comment]
Hi, @maskato.
Thank you for report. We found root cause.
New release that fixes issue will be available soon

**Comment by dimbez** [comment]
Hi, @maskato 
We released updated driver, it should fix your problem. You may find it [here](https://github.com/Aquantia/AQtion-esxi/releases/tag/v2.2.3.0-esxi1.5).

**Comment by maskato** [comment]
Thank you!

Looks good--quick and dirty:

[root@Z620:/usr/lib/vmware/vsan/bin] ./iperf3 -c 192.168.12.1 -P 4
Connecting to host 192.168.12.1, port 5201
[  4] local 192.168.12.62 port 30431 connected to 192.168.12.1 port 5201
[  6] local 192.168.12.62 port 20785 connected to 192.168.12.1 port 5201
[  8] local 192.168.12.62 port 51182 connected to 192.168.12.1 port 5201
[ 10] local 192.168.12.62 port 46804 connected to 192.168.12.1 port 5201
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec   274 MBytes  2.30 Gbits/sec  8634728   0.00 Bytes
[  6]   0.00-1.00   sec   273 MBytes  2.29 Gbits/sec  8634728   0.00 Bytes
[  8]   0.00-1.00   sec   303 MBytes  2.54 Gbits/sec  8634728   0.00 Bytes
[ 10]   0.00-1.00   sec   297 MBytes  2.49 Gbits/sec  8634728   0.00 Bytes
[SUM]   0.00-1.00   sec  1.12 GBytes  9.62 Gbits/sec  34538912
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]   1.00-2.00   sec   286 MBytes  2.40 Gbits/sec    0   0.00 Bytes
[  6]   1.00-2.00   sec   285 MBytes  2.39 Gbits/sec    0   0.00 Bytes
[  8]   1.00-2.00   sec   300 MBytes  2.52 Gbits/sec    0   0.00 Bytes
[ 10]   1.00-2.00   sec   285 MBytes  2.39 Gbits/sec    0   0.00 Bytes
[SUM]   1.00-2.00   sec  1.13 GBytes  9.70 Gbits/sec    0
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]   2.00-3.00   sec   280 MBytes  2.35 Gbits/sec    0   0.00 Bytes
[  6]   2.00-3.00   sec   281 MBytes  2.35 Gbits/sec    0   0.00 Bytes
[  8]   2.00-3.00   sec   297 MBytes  2.49 Gbits/sec    0   0.00 Bytes
[ 10]   2.00-3.00   sec   285 MBytes  2.39 Gbits/sec    0   0.00 Bytes
[SUM]   2.00-3.00   sec  1.12 GBytes  9.58 Gbits/sec    0
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]   3.00-4.00   sec   289 MBytes  2.43 Gbits/sec    0   0.00 Bytes
[  6]   3.00-4.00   sec   290 MBytes  2.43 Gbits/sec    0   0.00 Bytes
[  8]   3.00-4.00   sec   302 MBytes  2.53 Gbits/sec    0   0.00 Bytes
[ 10]   3.00-4.00   sec   289 MBytes  2.43 Gbits/sec    0   0.00 Bytes
[SUM]   3.00-4.00   sec  1.14 GBytes  9.82 Gbits/sec    0
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]   4.00-5.00   sec   285 MBytes  2.39 Gbits/sec    0   0.00 Bytes
[  6]   4.00-5.00   sec   285 MBytes  2.39 Gbits/sec    0   0.00 Bytes
[  8]   4.00-5.00   sec   309 MBytes  2.59 Gbits/sec    0   0.00 Bytes
[ 10]   4.00-5.00   sec   271 MBytes  2.27 Gbits/sec    0   0.00 Bytes
[SUM]   4.00-5.00   sec  1.12 GBytes  9.65 Gbits/sec    0
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]   5.00-6.00   sec   286 MBytes  2.40 Gbits/sec    0   0.00 Bytes
[  6]   5.00-6.00   sec   287 MBytes  2.40 Gbits/sec    0   0.00 Bytes
[  8]   5.00-6.00   sec   303 MBytes  2.54 Gbits/sec    0   0.00 Bytes
[ 10]   5.00-6.00   sec   289 MBytes  2.42 Gbits/sec    0   0.00 Bytes
[SUM]   5.00-6.00   sec  1.14 GBytes  9.77 Gbits/sec    0
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]   6.00-7.00   sec   286 MBytes  2.40 Gbits/sec    0   0.00 Bytes
[  6]   6.00-7.00   sec   286 MBytes  2.40 Gbits/sec    0   0.00 Bytes
[  8]   6.00-7.00   sec   297 MBytes  2.49 Gbits/sec    0   0.00 Bytes
[ 10]   6.00-7.00   sec   296 MBytes  2.49 Gbits/sec    0   0.00 Bytes
[SUM]   6.00-7.00   sec  1.14 GBytes  9.78 Gbits/sec    0
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]   7.00-8.00   sec   290 MBytes  2.44 Gbits/sec    0   0.00 Bytes
[  6]   7.00-8.00   sec   291 MBytes  2.44 Gbits/sec    0   0.00 Bytes
[  8]   7.00-8.00   sec   294 MBytes  2.47 Gbits/sec    0   0.00 Bytes
[ 10]   7.00-8.00   sec   292 MBytes  2.45 Gbits/sec    0   0.00 Bytes
[SUM]   7.00-8.00   sec  1.14 GBytes  9.79 Gbits/sec    0
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]   8.00-9.00   sec   285 MBytes  2.39 Gbits/sec    0   0.00 Bytes
[  6]   8.00-9.00   sec   286 MBytes  2.40 Gbits/sec    0   0.00 Bytes
[  8]   8.00-9.00   sec   298 MBytes  2.50 Gbits/sec    0   0.00 Bytes
[ 10]   8.00-9.00   sec   295 MBytes  2.48 Gbits/sec    0   0.00 Bytes
[SUM]   8.00-9.00   sec  1.14 GBytes  9.77 Gbits/sec    0
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
iperf3: getsockopt - Function not implemented
- - - - - - - - - - - - - - - - - - - - - - - - -
[  4]   9.00-10.00  sec   287 MBytes  2.41 Gbits/sec  4286332568   0.00 Bytes
[  6]   9.00-10.00  sec   287 MBytes  2.41 Gbits/sec  4286332568   0.00 Bytes
[  8]   9.00-10.00  sec   301 MBytes  2.53 Gbits/sec  4286332568   0.00 Bytes
[ 10]   9.00-10.00  sec   292 MBytes  2.45 Gbits/sec  4286332568   0.00 Bytes
[SUM]   9.00-10.00  sec  1.14 GBytes  9.79 Gbits/sec  -34538912
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec  2.78 GBytes  2.39 Gbits/sec    0             sender
[  4]   0.00-10.00  sec  2.78 GBytes  2.39 Gbits/sec                  receiver
[  6]   0.00-10.00  sec  2.78 GBytes  2.39 Gbits/sec    0             sender
[  6]   0.00-10.00  sec  2.78 GBytes  2.39 Gbits/sec                  receiver
[  8]   0.00-10.00  sec  2.93 GBytes  2.52 Gbits/sec    0             sender
[  8]   0.00-10.00  sec  2.93 GBytes  2.52 Gbits/sec                  receiver
[ 10]   0.00-10.00  sec  2.82 GBytes  2.43 Gbits/sec    0             sender
[ 10]   0.00-10.00  sec  2.82 GBytes  2.43 Gbits/sec                  receiver
[SUM]   0.00-10.00  sec  11.3 GBytes  **9.73 Gbits/sec**    0             sender
[SUM]   0.00-10.00  sec  11.3 GBytes  **9.73 Gbits/sec**                  receiver

iperf Done.
