### ISSUE TITLE
VLANs not working on ESXi 6.7U2?

### ISSUE THREAD

**Issue by ttuellmann** [Aquantia/AQtion-esxi#5]
I cannot get any VLAN traffic through the card on a 2018 Mac Mini with latest ESXi 6.7 (build 13473784).

Here is what I did:

* Create a vmkernel port `vmk1 `in a tagged VLAN
* Run `pktcap-uw --vmk vmk1` and `pktcap-uw --uplink vmnic0`
* Send traffic through the VLAN

![vswitch](https://user-images.githubusercontent.com/3656686/57516879-e7160c00-7315-11e9-8cca-cd39cbffc806.png)

I can see outgoing traffic in the `vmk1` capture but not `vmnic0`. 

I also tried to reconfigure the management interface to a tagged VLAN (and reconfigured the switch accordingly), which did not work either.

**Comment by dimbez** [comment]
Hi @ttuellmann 
Thank you for report. Unfortunately VLAN is still not supported. As soon as it is available we will let you know.

**Comment by dimbez** [comment]
Hi @ttuellmann. We are near to release driver that supports VLAN. It will be available in few days

**Comment by ttuellmann** [comment]
That’s great news. Thank you!

**Comment by dimbez** [comment]
Hi, @ttuellmann 
Please find release [ESXi-1.6](https://github.com/Aquantia/AQtion-esxi/releases/tag/v2.2.3.0-esxi1.6)

**Comment by ttuellmann** [comment]
Works without any issues so far.

Thanks a lot for implementing this!

**Comment by dimbez** [comment]
Thank you for confirmation!
