### ISSUE TITLE
In case someone has this same error when installing the driver

### ISSUE THREAD

**Issue by arielsanchezmora** [Aquantia/AQtion-esxi#7]
I had to do this on a 6.5 because of another hardware dependency that doesn't support 6.7.

[root@shuttle:/tmp] esxcli software vib install -v "/vmfs/volumes/LenovoEMC_PX4-300D_NFS_ISOs/net670-atlantic-v2.2.3.0-esxi1.6.x86_x64.vib"
 [DependencyError]
 VIB Aquantia_bootbank_net-aqn_1.6.7.0 violates extensibility rule checks: ['(line 30: col 0) Element vib failed to validate content']
 Please refer to the log file for more details.

**Notice the -f at the end of the new command**

[root@shuttle:/tmp] esxcli software vib install -v "/vmfs/volumes/LenovoEMC_PX4-300D_NFS_ISOs/net670-atlantic-v2.2.3.0-esxi1.6.x86_x64.vib" -f
Installation Result
   Message: The update completed successfully, but the system needs to be rebooted for the changes to be effective.
   Reboot Required: true
   VIBs Installed: Aquantia_bootbank_net-atlantic_v2.2.3.0-esxi1.6
   VIBs Removed:
   VIBs Skipped:

[root@shuttle:/tmp] vmware -v
VMware ESXi 6.5.0 build-5310538

**Comment by arielsanchezmora** [comment]
![image](https://user-images.githubusercontent.com/16085267/58710044-7351a700-8389-11e9-85fe-442c99eae2cf.png)
Seems to be working well :)

**Comment by dimbez** [comment]
Thank you, @arielsanchezmora , anyway all steps are described at [readme](https://github.com/Aquantia/AQtion-esxi/blob/master/README-ESXi.txt)
