### ISSUE TITLE
Support for ESXi Native Driver Stack

### ISSUE THREAD

**Issue by jonesxcli** [Aquantia/AQtion-esxi#8]
Will there be any support for ESXi Native Driver Stack ? 

Get-VMKLinuxDrivers -Cluster vsan

VMHost         VMKLinuxDriver                                                  
------         --------------                                                  
esxi00.esx.lab vmklinux_9_2_3_0,cnic_register,atlantic                         
esxi01.esx.lab vmklinux_9_2_3_0,cnic_register,atlantic,usb,xhci,hid,usb-storage
esxi03.esx.lab vmklinux_9_2_3_0,cnic_register,atlantic                         
esxi05.esx.lab vmklinux_9_2_3_0,cnic_register,atlantic   

Currently driver net-atlantic v2.2.3.0-esxi1.6 is running under VMKLinux driver stack. 

https://blogs.vmware.com/vsphere/2019/04/what-is-the-impact-of-the-vmklinux-driver-stack-deprecation.html 

Thank you

**Comment by cail** [comment]
Hello,
At now we can't share any plans or timelines of this.
Will update you if something'll come up.

**Comment by jonesxcli** [comment]
Now that 7.0 has gone GA, is there any plans for updating the drivers to use the native stack ?

**Comment by jdrozdnovak** [comment]
> Now that 7.0 has gone GA, is there any plans for updating the drivers to use the native stack ?
Since they moved under Marvell I don't see updates anymore so I am little afraid they won't :/

**Comment by dimbez** [comment]
Hello @sleepwalkerx97, we have driver supports native stack, please find it at the following [link](https://www.vmware.com/resources/compatibility/search.php?deviceCategory=io&details=1&VID=1d6a&page=1&display_interval=10&sortColumn=Partner&sortOrder=Asc)
