### ISSUE TITLE
Support for AQC111U

### ISSUE THREAD

**Issue by S-Fujisaki** [Aquantia/AQtion-esxi#9]
Is this driver surpport for AQC111U (USB3.0 -> 5Gbps Ethernet module) ?

**Comment by dimbez** [comment]
Hi, @S-Fujisaki it doesn't. We have other driver for AQC111U. If you are interesting we can send it to you for test purposes.

**Comment by S-Fujisaki** [comment]
Thank you for your reply.
I'm very interested in the AQC111U driver for VMware ESXi.
If you can, please send me by E-mail ( bigfan50cm@yahoo.co.jp )

**Comment by dimbez** [comment]
Hi, @S-Fujisaki, you may find driver package at the following location [v1.3.2.0-esxi1.0](https://github.com/Aquantia/aqc111u-esxi/releases/tag/v1.3.2.0-esxi1.0)
